//Eddy Campos Jiménez
//21 Agosto 2023
package CapaPresentacion;

import CapaEntidades.ExpedientesMascotas;
import CapaLogica.LExpedientes;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmExpedientes extends javax.swing.JInternalFrame {

    //Variable global
    DefaultTableModel modeloTabla;
    
    /**
     * Creates new form frmExpedientes
     */
    public frmExpedientes() {
        initComponents();
        
        try {
            ListarExpedientes("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
     //Método para preparar la tabla y que no se modifique
    public void PrepararTabla(){
        modeloTabla = new DefaultTableModel(){
            //Sobreescribe método para que no se pueda editar
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        tblExpedientes.setModel(modeloTabla);
        modeloTabla.addColumn("Código");
        modeloTabla.addColumn("Código Cliente");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Especie");
        modeloTabla.addColumn("Raza");
        modeloTabla.addColumn("Sexo");
        modeloTabla.addColumn("Fecha Nacimiento");
        modeloTabla.addColumn("Peso");        
    }
    
    //Método para generar la entidad del empleado
    public ExpedientesMascotas GenerarEntidadExpediente() throws Exception {
        ExpedientesMascotas expediente = new ExpedientesMascotas();
        
        try {
            if (txtCodigo.getText().equals("")) {
                expediente.setIdExpediente(-1);
            }
            else{
                expediente.setIdExpediente(Integer.parseInt(txtCodigo.getText()));
                expediente.setExiste(true);
            }
            
            //Convierte la fecha de date a localDate
            java.sql.Date fechaBaseDatos = java.sql.Date.valueOf(expediente.getFechaNacimiento());
            
            expediente.setIdCliente(Integer.parseInt(txtCodigoCliente.getText()));
            expediente.setNombre(txtNombre.getText());
            expediente.setEspecie(txtEspecie.getText());
            expediente.setRaza(txtRaza.getText());
            expediente.setSexo((String) ddlSexo.getSelectedItem());
            expediente.setFechaNacimiento(fechaBaseDatos.toLocalDate());
            expediente.setPeso(Integer.parseInt(txtPeso.getText()));
        } 
        catch (Exception e) {
            throw e;
        }
        
        return expediente;
    }

    //Método para listar los expedientes en la tabla
    public void ListarExpedientes(String condicion) throws Exception{
        try {
            LExpedientes logica = new LExpedientes();
            ResultSet datos;
            
            PrepararTabla();
            
            Object[] fila = new Object[8];
            datos = logica.ListarExpedientes(condicion, "");
            
            while (datos.next()) {
                fila[0] = datos.getInt("ID_EXPEDIENTE");
                fila[1] = datos.getString("ID_CLIENTE");
                fila[2] = datos.getString("NOMBRE");
                fila[3] = datos.getString("ESPECIE");
                fila[4] = datos.getString("RAZA");
                fila[5] = datos.getString("SEXO");
                fila[6] = datos.getString("FECHA_NACIMIENTO");
                fila[7] = datos.getString("PESO");

                
                modeloTabla.addRow(fila);
            }
        } 
        catch (Exception e) {
            throw  e;
        }
    }
    
    //Método para borrar las valores de las casillas
    public void LimpiarCasillas(){
        txtCodigo.setText("");
        txtCodigoCliente.setText("");
        txtNombre.setText("");
        txtRaza.setText("");
        txtEspecie.setText("");
        ddlSexo.setSelectedItem("MACHO");
        dtpFNacimiento.setDate(new Date());
        txtPeso.setText("");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigoCliente = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEspecie = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtRaza = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        ddlSexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        dtpFNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtPeso = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblExpedientes = new javax.swing.JTable();
        BtnLimpiar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("EXPEDIENTES");

        txtCodigo.setEnabled(false);
        jScrollPane1.setViewportView(txtCodigo);

        jLabel2.setText("Código");

        txtCodigoCliente.setEnabled(false);
        jScrollPane2.setViewportView(txtCodigoCliente);

        jLabel3.setText("Código Cliente");

        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtNombre);

        jLabel4.setText("Nombre");

        jScrollPane4.setViewportView(txtEspecie);

        jLabel5.setText("Especie");

        jScrollPane5.setViewportView(txtRaza);

        jLabel6.setText("Raza");

        ddlSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MACHO", "HEMBRA" }));

        jLabel7.setText("Sexo");

        jLabel8.setText("Fecha Nacimiento");

        jScrollPane6.setViewportView(txtPeso);

        jLabel9.setText("Peso");

        tblExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblExpedientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExpedientesMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblExpedientes);

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnLimpiar)
                        .addGap(31, 31, 31)
                        .addComponent(BtnGuardar)
                        .addGap(35, 35, 35)
                        .addComponent(BtnSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ddlSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 197, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel4)))
                                .addComponent(jLabel7))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dtpFNacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel8))
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(btnBuscarCliente)
                                            .addComponent(jScrollPane6))))))
                        .addComponent(jSeparator1)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddlSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnSalir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Click Boton Guardar
    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        try {
            LExpedientes logica = new LExpedientes();
            
            if (!txtNombre.getText().equals("") &&
            !txtCodigoCliente.getText().equals("") &&
            !txtEspecie.getText().equals("") &&
            !txtRaza.getText().equals("") &&
            !txtPeso.getText().equals("")){
                
                ExpedientesMascotas expediente = GenerarEntidadExpediente();
                
                if (!expediente.isExiste()) {
                    if (logica.InsertarExpediente(expediente) > 0) {
                        JOptionPane.showMessageDialog(this, logica.getMensaje());
                        LimpiarCasillas();
                        ListarExpedientes("");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, logica.getMensaje());
                    }
                }
                else{
                    if (logica.ActualizarExpediente(expediente) > 0) {
                        JOptionPane.showMessageDialog(this, logica.getMensaje());
                        LimpiarCasillas();
                        ListarExpedientes("");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, logica.getMensaje());
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos primero");
            }
            //Activa boton buscar cliente
            btnBuscarCliente.setEnabled(true);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    //Click boton salir
    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    //Click boton limpiar
    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        LimpiarCasillas();
        //Activa boton buscar cliente
        btnBuscarCliente.setEnabled(true);

    }//GEN-LAST:event_BtnLimpiarActionPerformed

    //Click a un elemento de a tabla
    private void tblExpedientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExpedientesMouseClicked
        //Llamar a obtener un expediente de la logica        
        try {
            LExpedientes logica = new LExpedientes();
            ExpedientesMascotas expediente;
            String condicion;

            //Si da dos clicks
            if (evt.getClickCount() == 2) {
                //Desactiva boton buscar cliente
                btnBuscarCliente.setEnabled(false);

                //Obtiene toda la fila
                int fila = tblExpedientes.rowAtPoint(evt.getPoint());
                txtCodigo.setText(tblExpedientes.getValueAt(fila, 0).toString());//Obtiene de la tabla
                
                condicion = String.format("ID_EXPEDIENTE= %s", txtCodigo.getText());
                expediente = logica.ObtenerCliente(condicion);//Obtiene del cliente
                
                 //Convierte la fecha de date a localDate
                java.sql.Date fechaBaseDatos = java.sql.Date.valueOf(expediente.getFechaNacimiento());
                
                txtCodigo.setText(String.valueOf(expediente.getIdExpediente()));
                txtCodigoCliente.setText(String.valueOf(expediente.getIdCliente()));
                txtNombre.setText(expediente.getNombre());
                txtEspecie.setText(expediente.getEspecie());
                txtRaza.setText(expediente.getRaza());
                txtPeso.setText(String.valueOf(expediente.getPeso()));
                ddlSexo.setSelectedItem(expediente.getSexo());
                dtpFNacimiento.setDate(fechaBaseDatos);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblExpedientesMouseClicked

    //Click boton buscar cliente
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        frmBuscarClientes buscarClientes = new frmBuscarClientes(null, true);
        
        //Cuando se cierra recupera el id
        buscarClientes.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e){
                try {
                    int id = buscarClientes.ObtenerId();
                    
                    if (id > -1) {
                        txtCodigoCliente.setText(String.valueOf(id));
                    }
                    else{
                        LimpiarCasillas();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
                }
            }
        
        });
        
        buscarClientes.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JComboBox<String> ddlSexo;
    private com.toedter.calendar.JDateChooser dtpFNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblExpedientes;
    private javax.swing.JTextPane txtCodigo;
    private javax.swing.JTextPane txtCodigoCliente;
    private javax.swing.JTextPane txtEspecie;
    private javax.swing.JTextPane txtNombre;
    private javax.swing.JTextPane txtPeso;
    private javax.swing.JTextPane txtRaza;
    // End of variables declaration//GEN-END:variables
}
