//Eddy Campos Jiménez
//19 Agosto 2023
package CapaPresentacion;

import CapaLogica.LFacturaTemporal;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setExtendedState(frmMenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuServicios = new javax.swing.JMenuItem();
        mnuExpedientes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuFactVenta = new javax.swing.JMenuItem();
        mnuFactCompra = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuInfoMensual = new javax.swing.JMenuItem();
        mnuInformeEmpleado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO");

        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        menu.setText("Datos");
        menu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        menu.add(mnuClientes);

        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        menu.add(mnuEmpleados);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        menu.add(mnuProductos);

        mnuServicios.setText("Servicios");
        mnuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServiciosActionPerformed(evt);
            }
        });
        menu.add(mnuServicios);

        mnuExpedientes.setText("Expedientes");
        mnuExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExpedientesActionPerformed(evt);
            }
        });
        menu.add(mnuExpedientes);

        jMenuBar1.add(menu);

        jMenu1.setText("Facturación");

        mnuFactVenta.setText("Venta");
        mnuFactVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFactVentaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFactVenta);

        mnuFactCompra.setText("Compra");
        mnuFactCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFactCompraActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFactCompra);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informes");

        mnuInfoMensual.setText("Mensual");
        mnuInfoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInfoMensualActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInfoMensual);

        mnuInformeEmpleado.setText("Empleados");
        mnuInformeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformeEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuInformeEmpleado);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
        
        //Ejecuta cuando se cierra el form 
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            // Método que se ejecuta al finalizar la aplicación
            LFacturaTemporal logicaFTemporal = new LFacturaTemporal();
            int result;
            try {
                result = logicaFTemporal.LimpiarFacturaTemporal();
            } catch (Exception ex) {
                Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }));
    }
    
    //Muestra el formulario Clientes
    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        frmClientes frm_Clientes = new frmClientes();
        escritorio.add(frm_Clientes);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Clientes.getSize();
        frm_Clientes.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Clientes.show();
    }//GEN-LAST:event_mnuClientesActionPerformed

    //Muestra el formulario Productos
    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        frmProductos frm_Productos = new frmProductos();
        escritorio.add(frm_Productos);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Productos.getSize();
        frm_Productos.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Productos.show();
    }//GEN-LAST:event_mnuProductosActionPerformed

    //Muestra el formulario Servicios
    private void mnuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServiciosActionPerformed
        frmServicios frm_Servicios = new frmServicios();
        escritorio.add(frm_Servicios);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Servicios.getSize();
        frm_Servicios.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Servicios.show();
    }//GEN-LAST:event_mnuServiciosActionPerformed

    //Muestra el formulario Empleados
    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
        frmEmpleados frm_Empleados = new frmEmpleados();
        
        escritorio.add(frm_Empleados);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Empleados.getSize();
        frm_Empleados.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Empleados.show();
    }//GEN-LAST:event_mnuEmpleadosActionPerformed

    //Muestra el formulario Expedientes
    private void mnuExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExpedientesActionPerformed
        frmExpedientes frm_Expedientes = new frmExpedientes();
        
        escritorio.add(frm_Expedientes);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Expedientes.getSize();
        frm_Expedientes.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Expedientes.show();
    }//GEN-LAST:event_mnuExpedientesActionPerformed

    //Muestra el formulario Fcatura Venta
    private void mnuFactVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFactVentaActionPerformed
        frmFacturaVenta frm_FVenta = new frmFacturaVenta();
        
        escritorio.add(frm_FVenta);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_FVenta.getSize();
        frm_FVenta.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_FVenta.show();
    }//GEN-LAST:event_mnuFactVentaActionPerformed

    //Muestra el formulario Fcatura Compra
    private void mnuFactCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFactCompraActionPerformed
        frmFacturaCompra frm_FCompra = new frmFacturaCompra();
        
        escritorio.add(frm_FCompra);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_FCompra.getSize();
        frm_FCompra.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_FCompra.show();
    }//GEN-LAST:event_mnuFactCompraActionPerformed

    //Muestra el formulario informacion mensual
    private void mnuInfoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInfoMensualActionPerformed
        frmInformeMensual frm_Informe = new frmInformeMensual();
        
        escritorio.add(frm_Informe);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Informe.getSize();
        frm_Informe.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Informe.show();
    }//GEN-LAST:event_mnuInfoMensualActionPerformed

    //Muestra el formulario informacion personal
    private void mnuInformeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformeEmpleadoActionPerformed
        frmInformeEmpleados frm_Informe = new frmInformeEmpleados();
        
        escritorio.add(frm_Informe);
        
        Dimension size = escritorio.getSize();
        Dimension sizeInter = frm_Informe.getSize();
        frm_Informe.setLocation(((int)size.getWidth() - (int)sizeInter.getWidth())/2,
                ((int)size.getHeight() - (int)sizeInter.getHeight())/2);
        frm_Informe.show();
    }//GEN-LAST:event_mnuInformeEmpleadoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuExpedientes;
    private javax.swing.JMenuItem mnuFactCompra;
    private javax.swing.JMenuItem mnuFactVenta;
    private javax.swing.JMenuItem mnuInfoMensual;
    private javax.swing.JMenuItem mnuInformeEmpleado;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuServicios;
    // End of variables declaration//GEN-END:variables
}
